### ISSUE TITLE
Request for devices enumeration

### ISSUE THREAD

**Issue by f4exb** [FreeSRP/libfreesrp#2]
FreeSRP looks like an interesting little gem but looking at the interface (a work in progress I know) I do not see any API to get an enumeration of the FreeSRP devices available to the system along with their serial number. As a consequence a method to open the device specifying the serial number should also be supplied. This will make it similar to BladeRF or HackRF.

**Comment by lukaslaobeyer** [comment]
You are right, the library does not yet handle detection/selection when multiple devices are used. I'll add this as soon as possible!
